// Master list of 200+ retro games. wikiTitle is the Wikipedia article title.
// build-database.js uses this to fetch descriptions + images from Wikipedia API.
module.exports = [
  // ── 1960s ──────────────────────────────────────────────────────────────────
  { id:"oxo", title:"OXO", year:1952, decade:"1960s", developer:"Alexander Douglas", publisher:"University of Cambridge", genre:"Puzzle", platform:"EDSAC", wikiTitle:"OXO (video game)" },
  { id:"tennis-for-two", title:"Tennis for Two", year:1958, decade:"1960s", developer:"William Higinbotham", publisher:"Brookhaven National Laboratory", genre:"Sports", platform:"Analog Computer / Oscilloscope", wikiTitle:"Tennis for Two" },
  { id:"spacewar", title:"Spacewar!", year:1962, decade:"1960s", developer:"Steve Russell et al.", publisher:"MIT", genre:"Space Combat", platform:"DEC PDP-1", wikiTitle:"Spacewar!" },
  { id:"sumerian-game", title:"The Sumerian Game", year:1964, decade:"1960s", developer:"Mabel Addis & William McKay", publisher:"IBM", genre:"Strategy", platform:"IBM 7090", wikiTitle:"The Sumerian Game" },
  { id:"hamurabi", title:"Hamurabi", year:1968, decade:"1960s", developer:"Doug Dyment", publisher:"DEC", genre:"Strategy", platform:"PDP-8 / BASIC", wikiTitle:"Hamurabi (video game)" },
  { id:"lunar-lander-1969", title:"Lunar Lander (1969)", year:1969, decade:"1960s", developer:"Jim Storer", publisher:"Lexington High School", genre:"Simulation", platform:"PDP-8", wikiTitle:"Lunar Lander (1969 video game)" },
  { id:"star-trek-basic", title:"Star Trek (BASIC)", year:1971, decade:"1960s", developer:"Mike Mayfield", publisher:"Public Domain", genre:"Strategy", platform:"BASIC / SDS Sigma 7", wikiTitle:"Star Trek (1971 video game)" },
  { id:"colossal-cave", title:"Colossal Cave Adventure", year:1976, decade:"1970s", developer:"Will Crowther & Don Woods", publisher:"Public Domain", genre:"Text Adventure", platform:"PDP-10", wikiTitle:"Colossal Cave Adventure" },

  // ── 1970s ──────────────────────────────────────────────────────────────────
  { id:"computer-space", title:"Computer Space", year:1971, decade:"1970s", developer:"Nolan Bushnell & Ted Dabney", publisher:"Nutting Associates", genre:"Space Shooter", platform:"Arcade", wikiTitle:"Computer Space" },
  { id:"galaxy-game", title:"Galaxy Game", year:1971, decade:"1970s", developer:"Bill Pitts & Hugh Tuck", publisher:"Self-published", genre:"Space Combat", platform:"PDP-11 Arcade Cabinet", wikiTitle:"Galaxy Game" },
  { id:"pong", title:"Pong", year:1972, decade:"1970s", developer:"Allan Alcorn", publisher:"Atari", genre:"Sports", platform:"Arcade", wikiTitle:"Pong" },
  { id:"space-race", title:"Space Race", year:1973, decade:"1970s", developer:"Atari", publisher:"Atari", genre:"Racing", platform:"Arcade", wikiTitle:"Space Race (video game)" },
  { id:"gotcha", title:"Gotcha", year:1973, decade:"1970s", developer:"Atari", publisher:"Atari", genre:"Maze", platform:"Arcade", wikiTitle:"Gotcha (video game)" },
  { id:"gran-trak-10", title:"Gran Trak 10", year:1974, decade:"1970s", developer:"Atari", publisher:"Atari", genre:"Racing", platform:"Arcade", wikiTitle:"Gran Trak 10" },
  { id:"tank", title:"Tank", year:1974, decade:"1970s", developer:"Lyle Rains", publisher:"Kee Games", genre:"Action", platform:"Arcade", wikiTitle:"Tank (video game)" },
  { id:"gun-fight", title:"Gun Fight", year:1975, decade:"1970s", developer:"Taito / Midway", publisher:"Midway", genre:"Action", platform:"Arcade", wikiTitle:"Gun Fight" },
  { id:"sea-wolf", title:"Sea Wolf", year:1976, decade:"1970s", developer:"Dave Nutting", publisher:"Midway", genre:"Action", platform:"Arcade", wikiTitle:"Sea Wolf (video game)" },
  { id:"night-driver", title:"Night Driver", year:1976, decade:"1970s", developer:"Atari", publisher:"Atari", genre:"Racing", platform:"Arcade", wikiTitle:"Night Driver (video game)" },
  { id:"sprint-2", title:"Sprint 2", year:1976, decade:"1970s", developer:"Atari", publisher:"Atari", genre:"Racing", platform:"Arcade", wikiTitle:"Sprint 2" },
  { id:"blockade", title:"Blockade", year:1976, decade:"1970s", developer:"Gremlin Industries", publisher:"Gremlin Industries", genre:"Action", platform:"Arcade", wikiTitle:"Blockade (video game)" },
  { id:"breakout", title:"Breakout", year:1976, decade:"1970s", developer:"Steve Wozniak", publisher:"Atari", genre:"Action", platform:"Arcade", wikiTitle:"Breakout (video game)" },
  { id:"death-race", title:"Death Race", year:1976, decade:"1970s", developer:"Howell Ivy", publisher:"Exidy", genre:"Racing", platform:"Arcade", wikiTitle:"Death Race (1976 video game)" },
  { id:"circus", title:"Circus", year:1977, decade:"1970s", developer:"Exidy", publisher:"Exidy", genre:"Action", platform:"Arcade", wikiTitle:"Circus (video game)" },
  { id:"atari-football", title:"Atari Football", year:1977, decade:"1970s", developer:"Atari", publisher:"Atari", genre:"Sports", platform:"Arcade", wikiTitle:"Atari Football" },
  { id:"space-wars", title:"Space Wars", year:1977, decade:"1970s", developer:"Larry Rosenthal", publisher:"Cinematronics", genre:"Space Combat", platform:"Arcade", wikiTitle:"Space Wars (video game)" },
  { id:"zork", title:"Zork", year:1977, decade:"1970s", developer:"Tim Anderson, Marc Blank, Bruce Daniels, Dave Lebling", publisher:"Infocom", genre:"Text Adventure", platform:"PDP-10 / Multiple", wikiTitle:"Zork" },
  { id:"fire-truck", title:"Fire Truck", year:1978, decade:"1970s", developer:"Atari", publisher:"Atari", genre:"Racing", platform:"Arcade", wikiTitle:"Fire Truck (video game)" },
  { id:"space-invaders", title:"Space Invaders", year:1978, decade:"1970s", developer:"Tomohiro Nishikado", publisher:"Taito", genre:"Fixed Shooter", platform:"Arcade", wikiTitle:"Space Invaders" },
  { id:"asteroids", title:"Asteroids", year:1979, decade:"1970s", developer:"Lyle Rains & Ed Logg", publisher:"Atari", genre:"Space Shooter", platform:"Arcade", wikiTitle:"Asteroids (video game)" },
  { id:"galaxian", title:"Galaxian", year:1979, decade:"1970s", developer:"Namco", publisher:"Namco", genre:"Fixed Shooter", platform:"Arcade", wikiTitle:"Galaxian" },
  { id:"lunar-lander", title:"Lunar Lander", year:1979, decade:"1970s", developer:"Atari", publisher:"Atari", genre:"Simulation", platform:"Arcade", wikiTitle:"Lunar Lander (video game)" },
  { id:"monaco-gp", title:"Monaco GP", year:1979, decade:"1970s", developer:"Sega", publisher:"Sega", genre:"Racing", platform:"Arcade", wikiTitle:"Monaco GP (video game)" },
  { id:"tail-gunner", title:"Tail Gunner", year:1979, decade:"1970s", developer:"Vectorbeam", publisher:"Vectorbeam", genre:"Space Shooter", platform:"Arcade", wikiTitle:"Tail Gunner (video game)" },
  { id:"adventure-2600", title:"Adventure", year:1979, decade:"1970s", developer:"Warren Robinett", publisher:"Atari", genre:"Action-Adventure", platform:"Atari 2600", wikiTitle:"Adventure (Atari 2600)" },
  { id:"temple-of-apshai", title:"Temple of Apshai", year:1979, decade:"1970s", developer:"Jon Freeman & Jeff Johnson", publisher:"Epyx", genre:"RPG", platform:"TRS-80 / Apple II", wikiTitle:"Temple of Apshai" },

  // ── 1980s ──────────────────────────────────────────────────────────────────
  { id:"missile-command", title:"Missile Command", year:1980, decade:"1980s", developer:"Dave Theurer", publisher:"Atari", genre:"Fixed Shooter", platform:"Arcade", wikiTitle:"Missile Command" },
  { id:"battlezone", title:"Battlezone", year:1980, decade:"1980s", developer:"Ed Rotberg", publisher:"Atari", genre:"Tank Shooter", platform:"Arcade", wikiTitle:"Battlezone (1980 video game)" },
  { id:"rally-x", title:"Rally-X", year:1980, decade:"1980s", developer:"Namco", publisher:"Namco", genre:"Racing / Maze", platform:"Arcade", wikiTitle:"Rally-X" },
  { id:"crazy-climber", title:"Crazy Climber", year:1980, decade:"1980s", developer:"Nichibutsu", publisher:"Nichibutsu", genre:"Action", platform:"Arcade", wikiTitle:"Crazy Climber" },
  { id:"berzerk", title:"Berzerk", year:1980, decade:"1980s", developer:"Alan McNeil", publisher:"Stern Electronics", genre:"Shooter", platform:"Arcade", wikiTitle:"Berzerk (video game)" },
  { id:"space-panic", title:"Space Panic", year:1980, decade:"1980s", developer:"Universal", publisher:"Universal", genre:"Platform", platform:"Arcade", wikiTitle:"Space Panic" },
  { id:"pac-man", title:"Pac-Man", year:1980, decade:"1980s", developer:"Toru Iwatani", publisher:"Namco", genre:"Maze", platform:"Arcade", wikiTitle:"Pac-Man" },
  { id:"centipede", title:"Centipede", year:1980, decade:"1980s", developer:"Ed Logg & Dona Bailey", publisher:"Atari", genre:"Shooter", platform:"Arcade", wikiTitle:"Centipede (video game)" },
  { id:"warlords", title:"Warlords", year:1980, decade:"1980s", developer:"Atari", publisher:"Atari", genre:"Action", platform:"Arcade", wikiTitle:"Warlords (video game)" },
  { id:"defender", title:"Defender", year:1981, decade:"1980s", developer:"Eugene Jarvis & Larry DeMar", publisher:"Williams Electronics", genre:"Shooter", platform:"Arcade", wikiTitle:"Defender (1981 video game)" },
  { id:"galaga", title:"Galaga", year:1981, decade:"1980s", developer:"Namco", publisher:"Namco", genre:"Fixed Shooter", platform:"Arcade", wikiTitle:"Galaga" },
  { id:"ms-pac-man", title:"Ms. Pac-Man", year:1981, decade:"1980s", developer:"Midway / General Computer Corporation", publisher:"Midway", genre:"Maze", platform:"Arcade", wikiTitle:"Ms. Pac-Man" },
  { id:"scramble", title:"Scramble", year:1981, decade:"1980s", developer:"Konami", publisher:"Konami", genre:"Shooter", platform:"Arcade", wikiTitle:"Scramble (video game)" },
  { id:"tempest", title:"Tempest", year:1981, decade:"1980s", developer:"Dave Theurer", publisher:"Atari", genre:"Shooter", platform:"Arcade", wikiTitle:"Tempest (video game)" },
  { id:"gorf", title:"Gorf", year:1981, decade:"1980s", developer:"Jamie Fenton", publisher:"Midway", genre:"Fixed Shooter", platform:"Arcade", wikiTitle:"Gorf" },
  { id:"wizard-of-wor", title:"Wizard of Wor", year:1981, decade:"1980s", developer:"Dave Nutting Associates", publisher:"Midway", genre:"Shooter", platform:"Arcade", wikiTitle:"Wizard of Wor" },
  { id:"qix", title:"Qix", year:1981, decade:"1980s", developer:"Randy & Sandy Pfeiffer", publisher:"Taito", genre:"Puzzle", platform:"Arcade", wikiTitle:"Qix" },
  { id:"donkey-kong", title:"Donkey Kong", year:1981, decade:"1980s", developer:"Shigeru Miyamoto", publisher:"Nintendo", genre:"Platform", platform:"Arcade", wikiTitle:"Donkey Kong (video game)" },
  { id:"frogger", title:"Frogger", year:1981, decade:"1980s", developer:"Konami", publisher:"Sega / Gremlin", genre:"Action", platform:"Arcade", wikiTitle:"Frogger" },
  { id:"ultima-i", title:"Ultima I", year:1981, decade:"1980s", developer:"Richard Garriott", publisher:"California Pacific Computer", genre:"RPG", platform:"Apple II", wikiTitle:"Ultima I: The First Age of Darkness" },
  { id:"stargate", title:"Stargate", year:1981, decade:"1980s", developer:"Eugene Jarvis & Larry DeMar", publisher:"Williams Electronics", genre:"Shooter", platform:"Arcade", wikiTitle:"Stargate (video game)" },
  { id:"wizardry", title:"Wizardry", year:1981, decade:"1980s", developer:"Andrew Greenberg & Robert Woodhead", publisher:"Sir-Tech", genre:"RPG", platform:"Apple II", wikiTitle:"Wizardry: Proving Grounds of the Mad Overlord" },
  { id:"tron", title:"Tron", year:1982, decade:"1980s", developer:"Midway", publisher:"Midway", genre:"Action", platform:"Arcade", wikiTitle:"Tron (video game)" },
  { id:"robotron-2084", title:"Robotron: 2084", year:1982, decade:"1980s", developer:"Eugene Jarvis & Larry DeMar", publisher:"Williams Electronics", genre:"Shooter", platform:"Arcade", wikiTitle:"Robotron: 2084" },
  { id:"joust", title:"Joust", year:1982, decade:"1980s", developer:"John Newcomer", publisher:"Williams Electronics", genre:"Platform / Action", platform:"Arcade", wikiTitle:"Joust (video game)" },
  { id:"moon-patrol", title:"Moon Patrol", year:1982, decade:"1980s", developer:"Irem", publisher:"Williams Electronics", genre:"Shooter", platform:"Arcade", wikiTitle:"Moon Patrol" },
  { id:"pole-position", title:"Pole Position", year:1982, decade:"1980s", developer:"Namco", publisher:"Namco / Atari", genre:"Racing", platform:"Arcade", wikiTitle:"Pole Position (video game)" },
  { id:"time-pilot", title:"Time Pilot", year:1982, decade:"1980s", developer:"Yoshiki Okamoto", publisher:"Konami", genre:"Shooter", platform:"Arcade", wikiTitle:"Time Pilot" },
  { id:"dig-dug", title:"Dig Dug", year:1982, decade:"1980s", developer:"Namco", publisher:"Namco / Atari", genre:"Action", platform:"Arcade", wikiTitle:"Dig Dug" },
  { id:"donkey-kong-jr", title:"Donkey Kong Jr.", year:1982, decade:"1980s", developer:"Nintendo", publisher:"Nintendo", genre:"Platform", platform:"Arcade", wikiTitle:"Donkey Kong Jr." },
  { id:"pengo", title:"Pengo", year:1982, decade:"1980s", developer:"Coreland / Sega", publisher:"Sega", genre:"Puzzle / Action", platform:"Arcade", wikiTitle:"Pengo (video game)" },
  { id:"burgertime", title:"BurgerTime", year:1982, decade:"1980s", developer:"Data East", publisher:"Data East / Bally Midway", genre:"Action", platform:"Arcade", wikiTitle:"BurgerTime" },
  { id:"mr-do", title:"Mr. Do!", year:1982, decade:"1980s", developer:"Universal", publisher:"Universal", genre:"Action", platform:"Arcade", wikiTitle:"Mr. Do!" },
  { id:"popeye", title:"Popeye", year:1982, decade:"1980s", developer:"Nintendo", publisher:"Nintendo", genre:"Action", platform:"Arcade", wikiTitle:"Popeye (video game)" },
  { id:"millipede", title:"Millipede", year:1982, decade:"1980s", developer:"Atari", publisher:"Atari", genre:"Shooter", platform:"Arcade", wikiTitle:"Millipede (video game)" },
  { id:"sinistar", title:"Sinistar", year:1982, decade:"1980s", developer:"Sam Dicker et al.", publisher:"Williams Electronics", genre:"Shooter", platform:"Arcade", wikiTitle:"Sinistar" },
  { id:"xevious", title:"Xevious", year:1982, decade:"1980s", developer:"Masanobu Endoh", publisher:"Namco", genre:"Shooter", platform:"Arcade", wikiTitle:"Xevious" },
  { id:"river-raid", title:"River Raid", year:1982, decade:"1980s", developer:"Carol Shaw", publisher:"Activision", genre:"Shooter", platform:"Atari 2600", wikiTitle:"River Raid" },
  { id:"pitfall", title:"Pitfall!", year:1982, decade:"1980s", developer:"David Crane", publisher:"Activision", genre:"Platform", platform:"Atari 2600", wikiTitle:"Pitfall!" },
  { id:"gravitar", title:"Gravitar", year:1982, decade:"1980s", developer:"Atari", publisher:"Atari", genre:"Shooter", platform:"Arcade", wikiTitle:"Gravitar" },
  { id:"zaxxon", title:"Zaxxon", year:1982, decade:"1980s", developer:"Sega", publisher:"Sega", genre:"Isometric Shooter", platform:"Arcade", wikiTitle:"Zaxxon" },
  { id:"qbert", title:"Q*bert", year:1982, decade:"1980s", developer:"Warren Davis & Jeff Lee", publisher:"Gottlieb", genre:"Puzzle / Action", platform:"Arcade", wikiTitle:"Q*bert" },
  { id:"mario-bros", title:"Mario Bros.", year:1983, decade:"1980s", developer:"Shigeru Miyamoto", publisher:"Nintendo", genre:"Platform", platform:"Arcade", wikiTitle:"Mario Bros." },
  { id:"star-wars-1983", title:"Star Wars", year:1983, decade:"1980s", developer:"Atari", publisher:"Atari", genre:"Space Shooter", platform:"Arcade", wikiTitle:"Star Wars (1983 video game)" },
  { id:"spy-hunter", title:"Spy Hunter", year:1983, decade:"1980s", developer:"Bally Midway", publisher:"Bally Midway", genre:"Racing / Shooter", platform:"Arcade", wikiTitle:"Spy Hunter" },
  { id:"crystal-castles", title:"Crystal Castles", year:1983, decade:"1980s", developer:"Atari", publisher:"Atari", genre:"Action", platform:"Arcade", wikiTitle:"Crystal Castles (video game)" },
  { id:"lode-runner", title:"Lode Runner", year:1983, decade:"1980s", developer:"Douglas E. Smith", publisher:"Broderbund", genre:"Platform / Puzzle", platform:"Apple II / Multiple", wikiTitle:"Lode Runner" },
  { id:"mule", title:"M.U.L.E.", year:1983, decade:"1980s", developer:"Dan Bunten Berry", publisher:"Electronic Arts", genre:"Strategy", platform:"Atari 8-bit / Multiple", wikiTitle:"M.U.L.E." },
  { id:"track-and-field", title:"Track & Field", year:1983, decade:"1980s", developer:"Konami", publisher:"Konami", genre:"Sports", platform:"Arcade", wikiTitle:"Track & Field (video game)" },
  { id:"tapper", title:"Tapper", year:1983, decade:"1980s", developer:"Marvin Glass and Associates", publisher:"Bally Midway", genre:"Action", platform:"Arcade", wikiTitle:"Tapper (video game)" },
  { id:"gyruss", title:"Gyruss", year:1983, decade:"1980s", developer:"Konami", publisher:"Konami / Centuri", genre:"Shooter", platform:"Arcade", wikiTitle:"Gyruss" },
  { id:"manic-miner", title:"Manic Miner", year:1983, decade:"1980s", developer:"Matthew Smith", publisher:"Bug-Byte", genre:"Platform", platform:"ZX Spectrum", wikiTitle:"Manic Miner" },
  { id:"archon", title:"Archon", year:1983, decade:"1980s", developer:"Free Fall Associates", publisher:"Electronic Arts", genre:"Strategy", platform:"Atari 8-bit / Apple II", wikiTitle:"Archon: The Light and the Dark" },
  { id:"dragons-lair", title:"Dragon's Lair", year:1983, decade:"1980s", developer:"Rick Dyer & Don Bluth", publisher:"Cinematronics", genre:"Laserdisc / Action", platform:"Arcade", wikiTitle:"Dragon's Lair" },
  { id:"1942", title:"1942", year:1984, decade:"1980s", developer:"Capcom", publisher:"Capcom", genre:"Shooter", platform:"Arcade", wikiTitle:"1942 (video game)" },
  { id:"punch-out-arcade", title:"Punch-Out!!", year:1984, decade:"1980s", developer:"Nintendo", publisher:"Nintendo", genre:"Boxing", platform:"Arcade", wikiTitle:"Punch-Out!! (arcade game)" },
  { id:"ghosts-n-goblins", title:"Ghosts 'n Goblins", year:1984, decade:"1980s", developer:"Capcom", publisher:"Capcom", genre:"Platform / Action", platform:"Arcade", wikiTitle:"Ghosts 'n Goblins" },
  { id:"karate-champ", title:"Karate Champ", year:1984, decade:"1980s", developer:"Data East", publisher:"Data East", genre:"Fighting", platform:"Arcade", wikiTitle:"Karate Champ" },
  { id:"paperboy", title:"Paperboy", year:1984, decade:"1980s", developer:"John Salwitz et al.", publisher:"Atari", genre:"Action", platform:"Arcade", wikiTitle:"Paperboy (video game)" },
  { id:"kings-quest", title:"King's Quest", year:1984, decade:"1980s", developer:"Roberta Williams", publisher:"Sierra On-Line", genre:"Adventure", platform:"PC/DOS", wikiTitle:"King's Quest" },
  { id:"elite", title:"Elite", year:1984, decade:"1980s", developer:"David Braben & Ian Bell", publisher:"Acornsoft", genre:"Space Trading / Simulation", platform:"BBC Micro / Multiple", wikiTitle:"Elite (video game)" },
  { id:"boulder-dash", title:"Boulder Dash", year:1984, decade:"1980s", developer:"Peter Liepa & Chris Gray", publisher:"First Star Software", genre:"Puzzle", platform:"Atari 8-bit / Multiple", wikiTitle:"Boulder Dash" },
  { id:"impossible-mission", title:"Impossible Mission", year:1984, decade:"1980s", developer:"Dennis Caswell", publisher:"Epyx", genre:"Action / Platform", platform:"Commodore 64", wikiTitle:"Impossible Mission" },
  { id:"duck-hunt", title:"Duck Hunt", year:1984, decade:"1980s", developer:"Nintendo", publisher:"Nintendo", genre:"Light Gun Shooter", platform:"NES", wikiTitle:"Duck Hunt" },
  { id:"excitebike", title:"Excitebike", year:1984, decade:"1980s", developer:"Nintendo", publisher:"Nintendo", genre:"Racing", platform:"NES / Arcade", wikiTitle:"Excitebike" },
  { id:"jet-set-willy", title:"Jet Set Willy", year:1984, decade:"1980s", developer:"Matthew Smith", publisher:"Software Projects", genre:"Platform", platform:"ZX Spectrum", wikiTitle:"Jet Set Willy" },
  { id:"kung-fu-master", title:"Kung-Fu Master", year:1984, decade:"1980s", developer:"Irem", publisher:"Irem / Data East", genre:"Beat 'em up", platform:"Arcade", wikiTitle:"Kung-Fu Master" },
  { id:"pac-land", title:"Pac-Land", year:1984, decade:"1980s", developer:"Namco", publisher:"Namco", genre:"Platform", platform:"Arcade", wikiTitle:"Pac-Land" },
  { id:"bomb-jack", title:"Bomb Jack", year:1984, decade:"1980s", developer:"Tehkan", publisher:"Tehkan", genre:"Platform", platform:"Arcade", wikiTitle:"Bomb Jack" },
  { id:"spy-vs-spy", title:"Spy vs. Spy", year:1984, decade:"1980s", developer:"Mike Riedel", publisher:"First Star Software", genre:"Action / Strategy", platform:"Commodore 64 / Multiple", wikiTitle:"Spy vs. Spy (video game)" },
  { id:"tetris", title:"Tetris", year:1984, decade:"1980s", developer:"Alexey Pajitnov", publisher:"Various", genre:"Puzzle", platform:"Elektronika 60 / Multiple", wikiTitle:"Tetris" },
  { id:"yie-ar-kung-fu", title:"Yie Ar Kung-Fu", year:1984, decade:"1980s", developer:"Konami", publisher:"Konami", genre:"Fighting", platform:"Arcade", wikiTitle:"Yie Ar Kung-Fu" },
  { id:"space-harrier", title:"Space Harrier", year:1985, decade:"1980s", developer:"Yu Suzuki", publisher:"Sega", genre:"Rail Shooter", platform:"Arcade", wikiTitle:"Space Harrier" },
  { id:"commando", title:"Commando", year:1985, decade:"1980s", developer:"Capcom", publisher:"Capcom", genre:"Run and Gun", platform:"Arcade", wikiTitle:"Commando (video game)" },
  { id:"gradius", title:"Gradius", year:1985, decade:"1980s", developer:"Konami", publisher:"Konami", genre:"Shooter", platform:"Arcade", wikiTitle:"Gradius" },
  { id:"gauntlet", title:"Gauntlet", year:1985, decade:"1980s", developer:"Ed Logg", publisher:"Atari", genre:"Dungeon Crawler", platform:"Arcade", wikiTitle:"Gauntlet (1985 video game)" },
  { id:"carmen-sandiego", title:"Where in the World Is Carmen Sandiego?", year:1985, decade:"1980s", developer:"Broderbund", publisher:"Broderbund", genre:"Educational", platform:"Apple II / Multiple", wikiTitle:"Where in the World Is Carmen Sandiego? (1985 video game)" },
  { id:"super-mario-bros", title:"Super Mario Bros.", year:1985, decade:"1980s", developer:"Shigeru Miyamoto & Takashi Tezuka", publisher:"Nintendo", genre:"Platform", platform:"NES", wikiTitle:"Super Mario Bros." },
  { id:"rushn-attack", title:"Rush'n Attack", year:1985, decade:"1980s", developer:"Konami", publisher:"Konami", genre:"Beat 'em up", platform:"Arcade", wikiTitle:"Rush'n Attack" },
  { id:"oregon-trail", title:"The Oregon Trail", year:1985, decade:"1980s", developer:"MECC", publisher:"MECC", genre:"Educational / Strategy", platform:"Apple II / DOS", wikiTitle:"The Oregon Trail (1985 video game)" },
  { id:"arkanoid", title:"Arkanoid", year:1986, decade:"1980s", developer:"Taito", publisher:"Taito", genre:"Action", platform:"Arcade", wikiTitle:"Arkanoid" },
  { id:"bubble-bobble", title:"Bubble Bobble", year:1986, decade:"1980s", developer:"Fukio Mitsuji", publisher:"Taito", genre:"Platform", platform:"Arcade", wikiTitle:"Bubble Bobble" },
  { id:"outrun", title:"Out Run", year:1986, decade:"1980s", developer:"Yu Suzuki", publisher:"Sega", genre:"Racing", platform:"Arcade", wikiTitle:"Out Run" },
  { id:"rampage", title:"Rampage", year:1986, decade:"1980s", developer:"Brian Colin & Jeff Nauman", publisher:"Midway", genre:"Action", platform:"Arcade", wikiTitle:"Rampage (video game)" },
  { id:"castlevania", title:"Castlevania", year:1986, decade:"1980s", developer:"Hitoshi Akamatsu", publisher:"Konami", genre:"Platform / Action", platform:"NES / Famicom Disk System", wikiTitle:"Castlevania (video game)" },
  { id:"metroid", title:"Metroid", year:1986, decade:"1980s", developer:"Nintendo R&D1", publisher:"Nintendo", genre:"Action-Adventure", platform:"NES / Famicom Disk System", wikiTitle:"Metroid (video game)" },
  { id:"kid-icarus", title:"Kid Icarus", year:1986, decade:"1980s", developer:"Nintendo R&D1", publisher:"Nintendo", genre:"Action / Platform", platform:"NES / Famicom Disk System", wikiTitle:"Kid Icarus" },
  { id:"fantasy-zone", title:"Fantasy Zone", year:1986, decade:"1980s", developer:"Sega", publisher:"Sega", genre:"Shooter", platform:"Arcade", wikiTitle:"Fantasy Zone" },
  { id:"solomons-key", title:"Solomon's Key", year:1986, decade:"1980s", developer:"Tecmo", publisher:"Tecmo", genre:"Puzzle / Platform", platform:"Arcade", wikiTitle:"Solomon's Key" },
  { id:"rolling-thunder", title:"Rolling Thunder", year:1986, decade:"1980s", developer:"Namco", publisher:"Namco", genre:"Action / Platform", platform:"Arcade", wikiTitle:"Rolling Thunder (video game)" },
  { id:"life-force", title:"Life Force", year:1986, decade:"1980s", developer:"Konami", publisher:"Konami", genre:"Shooter", platform:"Arcade", wikiTitle:"Life Force (video game)" },
  { id:"ikari-warriors", title:"Ikari Warriors", year:1986, decade:"1980s", developer:"SNK", publisher:"SNK / Tradewest", genre:"Run and Gun", platform:"Arcade", wikiTitle:"Ikari Warriors" },
  { id:"legend-of-zelda", title:"The Legend of Zelda", year:1986, decade:"1980s", developer:"Shigeru Miyamoto & Takashi Tezuka", publisher:"Nintendo", genre:"Action-Adventure", platform:"NES", wikiTitle:"The Legend of Zelda" },
  { id:"double-dragon", title:"Double Dragon", year:1987, decade:"1980s", developer:"Technos Japan", publisher:"Taito / Tradewest", genre:"Beat 'em up", platform:"Arcade", wikiTitle:"Double Dragon" },
  { id:"mega-man", title:"Mega Man", year:1987, decade:"1980s", developer:"Capcom", publisher:"Capcom", genre:"Platform / Action", platform:"NES", wikiTitle:"Mega Man (video game)" },
  { id:"r-type", title:"R-Type", year:1987, decade:"1980s", developer:"Irem", publisher:"Irem", genre:"Shooter", platform:"Arcade", wikiTitle:"R-Type" },
  { id:"metal-gear", title:"Metal Gear", year:1987, decade:"1980s", developer:"Hideo Kojima", publisher:"Konami", genre:"Stealth / Action", platform:"MSX2 / NES", wikiTitle:"Metal Gear (video game)" },
  { id:"shinobi", title:"Shinobi", year:1987, decade:"1980s", developer:"Sega", publisher:"Sega", genre:"Action / Platform", platform:"Arcade", wikiTitle:"Shinobi (1987 video game)" },
  { id:"after-burner", title:"After Burner", year:1987, decade:"1980s", developer:"Yu Suzuki", publisher:"Sega", genre:"Rail Shooter", platform:"Arcade", wikiTitle:"After Burner" },
  { id:"operation-wolf", title:"Operation Wolf", year:1987, decade:"1980s", developer:"Taito", publisher:"Taito", genre:"Light Gun Shooter", platform:"Arcade", wikiTitle:"Operation Wolf" },
  { id:"contra", title:"Contra", year:1987, decade:"1980s", developer:"Konami", publisher:"Konami", genre:"Run and Gun", platform:"Arcade / NES", wikiTitle:"Contra (video game)" },
  { id:"street-fighter", title:"Street Fighter", year:1987, decade:"1980s", developer:"Takashi Nishiyama & Hiroshi Matsumoto", publisher:"Capcom", genre:"Fighting", platform:"Arcade", wikiTitle:"Street Fighter (video game)" },
  { id:"pirates", title:"Pirates!", year:1987, decade:"1980s", developer:"Sid Meier", publisher:"MicroProse", genre:"Strategy / Action", platform:"Commodore 64 / Multiple", wikiTitle:"Pirates! (video game)" },
  { id:"maniac-mansion", title:"Maniac Mansion", year:1987, decade:"1980s", developer:"Ron Gilbert & Gary Winnick", publisher:"LucasArts", genre:"Point-and-Click Adventure", platform:"Commodore 64 / Multiple", wikiTitle:"Maniac Mansion" },
  { id:"road-blasters", title:"Road Blasters", year:1987, decade:"1980s", developer:"Atari", publisher:"Atari", genre:"Racing / Shooter", platform:"Arcade", wikiTitle:"Road Blasters" },
  { id:"rastan", title:"Rastan", year:1987, decade:"1980s", developer:"Taito", publisher:"Taito", genre:"Beat 'em up", platform:"Arcade", wikiTitle:"Rastan" },
  { id:"punch-out-nes", title:"Mike Tyson's Punch-Out!!", year:1987, decade:"1980s", developer:"Nintendo", publisher:"Nintendo", genre:"Boxing", platform:"NES", wikiTitle:"Mike Tyson's Punch-Out!!" },
  { id:"bionic-commando", title:"Bionic Commando", year:1987, decade:"1980s", developer:"Capcom", publisher:"Capcom", genre:"Action / Platform", platform:"Arcade", wikiTitle:"Bionic Commando (1987 video game)" },
  { id:"dragon-spirit", title:"Dragon Spirit", year:1987, decade:"1980s", developer:"Namco", publisher:"Namco", genre:"Shooter", platform:"Arcade", wikiTitle:"Dragon Spirit" },
  { id:"altered-beast", title:"Altered Beast", year:1988, decade:"1980s", developer:"Sega", publisher:"Sega", genre:"Beat 'em up", platform:"Arcade", wikiTitle:"Altered Beast" },
  { id:"mega-man-2", title:"Mega Man 2", year:1988, decade:"1980s", developer:"Capcom", publisher:"Capcom", genre:"Platform / Action", platform:"NES", wikiTitle:"Mega Man 2" },
  { id:"ghouls-n-ghosts", title:"Ghouls 'n Ghosts", year:1988, decade:"1980s", developer:"Capcom", publisher:"Capcom", genre:"Platform / Action", platform:"Arcade", wikiTitle:"Ghouls 'n Ghosts" },
  { id:"super-mario-bros-3", title:"Super Mario Bros. 3", year:1988, decade:"1980s", developer:"Shigeru Miyamoto", publisher:"Nintendo", genre:"Platform", platform:"NES / Famicom", wikiTitle:"Super Mario Bros. 3" },
  { id:"ninja-gaiden", title:"Ninja Gaiden", year:1988, decade:"1980s", developer:"Tecmo", publisher:"Tecmo", genre:"Action / Platform", platform:"Arcade / NES", wikiTitle:"Ninja Gaiden (NES video game)" },
  { id:"blaster-master", title:"Blaster Master", year:1988, decade:"1980s", developer:"Sunsoft", publisher:"Sunsoft", genre:"Action / Platform", platform:"NES", wikiTitle:"Blaster Master" },
  { id:"bad-dudes", title:"Bad Dudes vs. DragonNinja", year:1988, decade:"1980s", developer:"Data East", publisher:"Data East", genre:"Beat 'em up", platform:"Arcade", wikiTitle:"Bad Dudes vs. DragonNinja" },
  { id:"toobin", title:"Toobin'", year:1988, decade:"1980s", developer:"Atari", publisher:"Atari", genre:"Action / Sports", platform:"Arcade", wikiTitle:"Toobin'" },
  { id:"strider", title:"Strider", year:1989, decade:"1980s", developer:"Capcom", publisher:"Capcom", genre:"Action / Platform", platform:"Arcade", wikiTitle:"Strider (1989 video game)" },
  { id:"golden-axe", title:"Golden Axe", year:1989, decade:"1980s", developer:"Sega", publisher:"Sega", genre:"Beat 'em up", platform:"Arcade", wikiTitle:"Golden Axe (video game)" },
  { id:"final-fight", title:"Final Fight", year:1989, decade:"1980s", developer:"Capcom", publisher:"Capcom", genre:"Beat 'em up", platform:"Arcade", wikiTitle:"Final Fight" },
  { id:"tmnt-arcade", title:"Teenage Mutant Ninja Turtles", year:1989, decade:"1980s", developer:"Konami", publisher:"Konami", genre:"Beat 'em up", platform:"Arcade", wikiTitle:"Teenage Mutant Ninja Turtles (arcade game)" },
  { id:"simcity", title:"SimCity", year:1989, decade:"1980s", developer:"Will Wright", publisher:"Maxis", genre:"City Building / Simulation", platform:"Macintosh / PC", wikiTitle:"SimCity (1989 video game)" },
  { id:"batman-1989", title:"Batman", year:1989, decade:"1980s", developer:"Sunsoft", publisher:"Sunsoft", genre:"Platform / Action", platform:"NES", wikiTitle:"Batman (1989 video game)" },
  { id:"ducktales", title:"DuckTales", year:1989, decade:"1980s", developer:"Capcom", publisher:"Capcom", genre:"Platform", platform:"NES", wikiTitle:"DuckTales (video game)" },
  { id:"klax", title:"Klax", year:1989, decade:"1980s", developer:"Mark Stephen Pierce & Dave Akers", publisher:"Atari", genre:"Puzzle", platform:"Arcade", wikiTitle:"Klax (video game)" },
  { id:"prince-of-persia", title:"Prince of Persia", year:1989, decade:"1980s", developer:"Jordan Mechner", publisher:"Broderbund", genre:"Platform / Action", platform:"Apple II / DOS", wikiTitle:"Prince of Persia (1989 video game)" },
  { id:"space-quest", title:"Space Quest", year:1986, decade:"1980s", developer:"Mark Crowe & Scott Murphy", publisher:"Sierra On-Line", genre:"Adventure", platform:"PC/DOS", wikiTitle:"Space Quest" },
  { id:"ultima-iv", title:"Ultima IV", year:1985, decade:"1980s", developer:"Richard Garriott", publisher:"Origin Systems", genre:"RPG", platform:"Apple II / Multiple", wikiTitle:"Ultima IV: Quest of the Avatar" },
  { id:"flight-simulator", title:"Microsoft Flight Simulator", year:1982, decade:"1980s", developer:"Bruce Artwick / subLOGIC", publisher:"Microsoft", genre:"Simulation", platform:"PC/DOS", wikiTitle:"Microsoft Flight Simulator (1982 video game)" },
  { id:"police-quest", title:"Police Quest", year:1987, decade:"1980s", developer:"Jim Walls", publisher:"Sierra On-Line", genre:"Adventure", platform:"PC/DOS", wikiTitle:"Police Quest: In Pursuit of the Death Angel" },
  { id:"leisure-suit-larry", title:"Leisure Suit Larry", year:1987, decade:"1980s", developer:"Al Lowe", publisher:"Sierra On-Line", genre:"Adventure", platform:"PC/DOS", wikiTitle:"Leisure Suit Larry in the Land of the Lounge Lizards" },
  { id:"head-over-heels", title:"Head Over Heels", year:1987, decade:"1980s", developer:"Jon Ritman & Bernie Drummond", publisher:"Ocean Software", genre:"Isometric Action", platform:"ZX Spectrum / Multiple", wikiTitle:"Head Over Heels (video game)" },
  { id:"jackal", title:"Jackal", year:1986, decade:"1980s", developer:"Konami", publisher:"Konami", genre:"Run and Gun", platform:"Arcade", wikiTitle:"Jackal (video game)" },
  { id:"castlevania-ii", title:"Castlevania II: Simon's Quest", year:1987, decade:"1980s", developer:"Konami", publisher:"Konami", genre:"Action RPG", platform:"NES", wikiTitle:"Castlevania II: Simon's Quest" },
  { id:"mega-man-3", title:"Mega Man 3", year:1989, decade:"1980s", developer:"Capcom", publisher:"Capcom", genre:"Platform / Action", platform:"NES", wikiTitle:"Mega Man 3" },
  { id:"chip-n-dale", title:"Chip 'n Dale Rescue Rangers", year:1989, decade:"1980s", developer:"Capcom", publisher:"Capcom", genre:"Platform", platform:"NES", wikiTitle:"Chip 'n Dale Rescue Rangers (video game)" },
  { id:"battletoads", title:"Battletoads", year:1989, decade:"1980s", developer:"Rare", publisher:"Tradewest", genre:"Beat 'em up / Platform", platform:"Arcade / NES", wikiTitle:"Battletoads" },
  { id:"q10-tankbuster", title:"Xenon", year:1988, decade:"1980s", developer:"Bitmap Brothers", publisher:"Bitmap Brothers", genre:"Shooter", platform:"Amiga / Atari ST", wikiTitle:"Xenon (video game)" },
  { id:"speedball", title:"Speedball", year:1988, decade:"1980s", developer:"Bitmap Brothers", publisher:"Bitmap Brothers", genre:"Sports", platform:"Amiga / Atari ST", wikiTitle:"Speedball (video game)" },
  { id:"turrican", title:"Turrican", year:1989, decade:"1980s", developer:"Factor 5", publisher:"Rainbow Arts", genre:"Platform / Shooter", platform:"Commodore 64 / Amiga", wikiTitle:"Turrican" },
  { id:"lemmings-early", title:"Rick Dangerous", year:1989, decade:"1980s", developer:"Core Design", publisher:"Firebird", genre:"Platform", platform:"Amiga / Atari ST", wikiTitle:"Rick Dangerous" },
  { id:"another-world", title:"Out of This World", year:1991, decade:"1980s", developer:"Éric Chahi", publisher:"Delphine Software", genre:"Action / Adventure", platform:"Amiga / DOS", wikiTitle:"Another World (video game)" },
  { id:"gauntlet-ii", title:"Gauntlet II", year:1986, decade:"1980s", developer:"Ed Logg", publisher:"Atari", genre:"Dungeon Crawler", platform:"Arcade", wikiTitle:"Gauntlet II" },
  { id:"rygar", title:"Rygar", year:1986, decade:"1980s", developer:"Tecmo", publisher:"Tecmo", genre:"Action / Platform", platform:"Arcade", wikiTitle:"Rygar" },
  { id:"ghosts-n-goblins-nes", title:"Ghouls 'n Ghosts (NES)", year:1988, decade:"1980s", developer:"Capcom", publisher:"Capcom", genre:"Platform", platform:"NES", wikiTitle:"Ghouls 'n Ghosts" },
  { id:"image-fight", title:"Image Fight", year:1988, decade:"1980s", developer:"Irem", publisher:"Irem", genre:"Shooter", platform:"Arcade", wikiTitle:"Image Fight" },
  { id:"twin-cobra", title:"Twin Cobra", year:1987, decade:"1980s", developer:"Toaplan", publisher:"Taito / Romstar", genre:"Shooter", platform:"Arcade", wikiTitle:"Twin Cobra" },
  { id:"truxton", title:"Truxton", year:1988, decade:"1980s", developer:"Toaplan", publisher:"Toaplan", genre:"Shooter", platform:"Arcade", wikiTitle:"Truxton" },
  { id:"mercs", title:"Mercs", year:1989, decade:"1980s", developer:"Capcom", publisher:"Capcom", genre:"Run and Gun", platform:"Arcade", wikiTitle:"Mercs (video game)" },
  { id:"wrestlefest", title:"WrestleFest", year:1989, decade:"1980s", developer:"Technos Japan", publisher:"Technos Japan", genre:"Wrestling", platform:"Arcade", wikiTitle:"WWF WrestleFest" },
  { id:"galaxy-force-ii", title:"Galaxy Force II", year:1988, decade:"1980s", developer:"Sega", publisher:"Sega", genre:"Rail Shooter", platform:"Arcade", wikiTitle:"Galaxy Force II" },
  { id:"thunder-blade", title:"Thunder Blade", year:1987, decade:"1980s", developer:"Sega", publisher:"Sega", genre:"Shooter", platform:"Arcade", wikiTitle:"Thunder Blade" },
];
